apiVersion: apps/v1
kind: Deployment
metadata:
  name: bb-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: bb-site
        image: irahul1/trial_site:0.7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort : 3001
---
apiVersion: v1
kind: Service
metadata:
  name: bb-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - protocol: TCP
    port: 6000
    targetPort: 3001
    nodePort: 30001

