# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totalsolv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date posted'),
        ),
    ]
